name: Refresh dSYMs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  refresh-dsyms:
    runs-on: macos-latest
    steps:
      - name: fastlane refresh_dsyms
        run: bundle exec fastlane refresh_dsyms
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
